version: 2
on: 
  pull_request:
  workflow_dispatch:

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"