name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22' 

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    - name: Building dependencies
      run: |
        cd frontend
        npm ci
        npx ng build
        mkdir ../backend/cmd/strichliste/frontendDist
        cp -r dist/frontend/browser ../backend/cmd/strichliste/frontendDist
    - name: Run Unit Tests  
      run: |
          cd backend 
          go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Coverage-Report
        path: backend/coverage.html
  
    - name: Check Code Formatting
      run: |
        cd backend
        go fmt ./...

    - name: Copy files via SCP action
      uses: appleboy/scp-action@master
      with:
        host: dhbw.hoenle.xyz
        username: group7
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./backend/coverage.html"
        target: "/var/www/group7/coverage.html"
  
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v6
      with:
        name: ImageGruppe7
        push: false
        tags: ghcr.io/aronse1/app:latest
        load: true

    - name: Run Container
      run: docker run -d -p 8080:8080 ghcr.io/aronse1/app:latest

    - name: Smoke weed everyday
      run: |
        cd backend
        go run ./cmd/smoketest/ 

    - name: Push to Dogga HUP
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/aronse1/app:latest
    

    - name: Insult Doomas
      run: echo "Doomas is a noob"

    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: dhbw.hoenle.xyz
        username: group7
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          IMAGE_NAME=ghcr.io/aronse1/app:latest
          CONTAINER_NAME=Gruppe7
            

          docker pull ImageGruppe7
            

          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
            
          # Start the new container
          docker run -d --name $CONTAINER_NAME -p 7777:7777 ImageGruppe7
