name: Trivy Pipeline

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:




jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

        
    - name: Setup Trivy
      uses: aquasecurity/trivy-action@v0.3.0
      with:
        scan-type: filesystem
        severity: CRITICAL,HIGH
        ignore-unfixed: true

        
    - name: Run Trivy Scan
      run: trivy fs .