name: Trivy Pipeline

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:




jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: filesystem
          severity: CRITICAL,HIGH
          ignore-unfixed: true
      - name: Run Trivy 
        run: trivy fs --format template --template "@html.tpl" --output report.html . 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Coverage-Report
          path: report.html

      - name: Copy files via SCP action
        uses: appleboy/scp-action@master
        with:
          host: dhbw.hoenle.xyz
          username: group7
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "report.html"
          target: "/var/www/group7/report.html"